version: "3.4"

services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      args:
        - FRONTEND_DEV_PORT=${FRONTEND_DEV_PORT}
    restart: unless-stopped
    ports: 
      - ${FRONTEND_DEV_PORT}:${FRONTEND_DEV_PORT}
    volumes:
      - ./client/src:/client/src
    # - /client/node_modules